version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
