name: 'Enable Pull Request Automerge'
description: 'A GitHub action to enable auto-merge on a pull request'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository containing the pull request'
    default: ${{ github.repository }}
  pull-request-number:
    description: 'The number of the target pull request'
    required: true
  merge-method:
    description: 'The merge method to use. `merge`, `rebase` or `squash`.'
    default: merge
runs:
  using: composite
  steps:
    - name: Lowercase
      id: lowercase
      shell: bash
      run: |
        echo merge-method=$(echo "${{ inputs.merge-method }}" | tr '[:upper:]' '[:lower:]') >> $GITHUB_OUTPUT

    - name: Enable automerge
      shell: bash
      run: gh pr merge -R "${{ inputs.repository }}" --${{ steps.lowercase.outputs.merge-method }} --auto "${{ inputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ inputs.token }}
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
