name: 'Enable Pull Request Automerge'
description: 'A GitHub action to enable auto-merge on a pull request'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository containing the pull request'
    default: ${{ github.repository }}
  pull-request-number:
    description: 'The number of the target pull request'
    required: true
  merge-method:
    description: 'The merge method to use. `merge`, `rebase` or `squash`.'
    default: MERGE
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
