name: 'Enable Pull Request Automerge'
description: 'A GitHub action to enable auto-merge on a pull request'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  repository:
    description: 'The target GitHub repository containing the pull request'
    default: ${{ github.repository }}
  pull-request-number:
    description: 'The number of the target pull request'
    required: true
  merge-method:
    description: 'The merge method to use. `merge`, `rebase` or `squash`.'
    default: merge
  delete-branch:
    description: 'Delete the local and remote branch after merge'
    default: false
runs:
  using: composite
  steps:
    - name: Lowercase
      id: lowercase
      shell: bash
      run: |
        INPUT=${{ inputs.merge-method }}; echo "merge-method=${INPUT,,}" >> $GITHUB_OUTPUT

    - name: Delete branch
      id: delete-branch
      shell: bash
      run: |
        if [[ ${{ inputs.delete-branch }} == "true" ]]; then
          echo "flag=--delete-branch" >> $GITHUB_OUTPUT
        else
          echo "flag=" >> $GITHUB_OUTPUT
        fi

    - name: Enable automerge
      shell: bash
      run: gh pr merge -R "${{ inputs.repository }}" --${{ steps.lowercase.outputs.merge-method }} --auto ${{ steps.delete-branch.outputs.flag }} "${{ inputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ inputs.token }}
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
